# general settings
name: IconVSR_JiLin189
model_type: VideoRecurrentModel
scale: 4
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    dataroot_gt: ../vsr_dataset/jilin_189/train/GT
    dataroot_lq: ../vsr_dataset/jilin_189/train/LR4x
    meta_info_file: ../vsr_dataset/jilin_189/meta_info_jilin189_GT.txt  # training Jilin189
    val_partition: REDS4  # you should modify the file of REDS4 to load Jilin12
    test_mode: False
    io_backend:
      type: disk

    num_frame: 15
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4 #用法和格式跟RES4一样 只是数据集替换为jilin_12 验证集
    type: VideoRecurrentTestDataset
    dataroot_gt: ../vsr_dataset/jilin_189/eval/GT  # validation Jilin12
    dataroot_lq: ../vsr_dataset/jilin_189/eval/LR4x

    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed

# network structures
network_g:
  type: IconVSR
  num_feat: 64
  num_block: 30
  keyframe_stride: 5
  temporal_padding: 2
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
  edvr_path: experiments/pretrained_models/edvr/EDVR_REDS_pretrained_for_IconVSR-f62a2f1e.pth

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
