# general settings
name: IBRN_ORIGIN_2e-4_300k_b1
# experiments_root: exp_video2/vimeo90k_retrain2
model_type: BasicVSRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KRecurrentDataset
    scale: 4
    dataroot_gt: ../vsr_dataset/vimeo90k/GT
    dataroot_lq: ../vsr_dataset/vimeo90k/BIx4
    meta_info_file: ../vsr_dataset/vimeo90k/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    is_train: true
    num_frame: -1
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 200
    prefetch_mode: ~
    pin_memory: true

  val:
    name: Vid4
    type: VidTestDataset #原VidTestDataset
    dataroot_gt: ../vsr_dataset/Vid4/GT
    dataroot_lq: ../vsr_dataset/Vid4/BIx4
    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed

    # name: Vimeo90K
    # type: Vimeo90KDataset
    # dataroot_gt: /media/disk/silence/data/vimeo_septuplet/sequences
    # dataroot_lq: /media/disk/silence/data/vimeo_septuplet/lr_bi_sequences
    # meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_test_medium_GT.txt
    # io_backend:
    #   type: disk

    # is_train: false
    # num_frame: 7
    # gt_size: ~
    # interval_list: [1]
    # random_reverse: false
    # use_flip: false
    # use_rot: false

# network structures
network_g:
  type: BasicVSR_V4
  num_feat: 64
  extract_block: 12
  num_block: 30
  resType: ResidualBlock_CA
  use_deblur: true

# path
path:
  pretrain_network_g: #exp_video2/vimeo90k_retrain2/BasicVSR_V4_1e-6_100k_b6_stage4/models/net_g_100000.pth #exp_video2/V4_4e-4_REDS_BI_x4/models/net_g_235000.pth
  strict_load_g: false
  resume_state: #experiments/IBRN_BasicVSR_V4_1e-6_100k_b6_stage5/training_states/5000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    # periods: [250000, 250000, 250000, 250000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  # fix_iter: 5000
  # spynet_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
